swagger: "2.0"
info:
  title: Api Geolocalização
  description: Api codificação de endereços e geolocalização.
  termsOfService: A ser definido
  contact:
    email: contele@hotmail.com
  license:
    name: "Contele"
    url: "https://contele.com.br"
  version: 0.0.1
host: api.example.com
basePath: /v1
tags:
- name: "geocoding"
  description: "Busca dados de geolocalização"
schemes:
  - https
  - http
paths:
  /geocode:
    get:
      tags:
      - "geocoding"
      summary: Endpoint para geolocalização de coordenadas
      description: Retorna multiplos endereços conforme as coordenadas passadas na requisição.
      produces:
        - application/json
      parameters:
        - name: coordinates
          in: query
          required: true
          description: "Array de coordenadas enviado na requisição"
          type: array
          items:
           type: string
           default: -22.8574076,-48.4632952
        - name: source
          in: query
          required: true
          description: "Enum que identifica a plataforma de geolocalização"
          type: string
          enum:
            - google
            - geoportal
            - default
          default: default
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/CoordenadasResponse"
  /address:
    get:
      tags:
      - "geocoding"
      summary: Endpoint para geolocalização de endereços 
      description: Retorna multiplas coordenadas conforme endereços passados na requisição.
      parameters:
        - name: addresses
          in: query
          required: true
          description: "Array de endereços enviado na requisição"
          type: array
          items:
           type: string
          default: rua das margaridas
        - name: source
          in: query
          required: true
          description: "Enum que identifica a plataforma de geolocalização"
          type: string
          enum:
            - google
            - geoportal
            - default
          default: default
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/EnderecosResponse"
definitions:
  CoordenadasResponse:
    type: object
    properties:
      formattedAddress:
        type: string
      latitude:
        type: string
      longitude:
        type: string
      extra:
        type: object
        properties:
          premise:
            type: boolean
          subpremise:
            type: boolean
          neighborhood:
            type: string
          establishment:
            type: boolean
      administrativeLevels:
        type: array
        items:
          type: string
      streetNumber:
        type: string
      streetName:
        type: string
      city:
        type: string
      country:
        type: string
      countryCode:
        type: string
      zipcode:
        type: string
      state:
        type: string
      accuracy:
        type: string
      provider:
        type: boolean
        default: false
      responseDefinition:
        type: string
        default: simple
      status:
        type: string
  EnderecosResponse:
    type: object
    properties:
      formattedAddress:
        type: string
      latitude:
        type: string
      longitude:
        type: string
      extra:
        type: object
        properties:
          premise:
            type: boolean
          subpremise:
            type: boolean
          neighborhood:
            type: string
          establishment:
            type: boolean
      administrativeLevels:
        type: array
        items: 
          type: string
      streetNumber:
        type: string
      streetName:
        type: string
      city:
        type: string
      country:
        type: string
      countryCode:
        type: string
      zipcode:
        type: string
      state:
        type: string
      accuracy:
        type: string
      provider:
        type: boolean
        default: false
      responseDefinition:
        type: string
        default: simple
      status:
        type: string